### ISSUE TITLE
PHP requirement

### ISSUE THREAD

**Issue by ghost** [lokamaya/ModLDAP#1]
Does this require LDAP to be enabled in the server's PHP? If so, perhaps there should be a check for that before installation?

**Comment by lokamaya** [comment]
Edited README.md, and added **Requirement**

## Requirement
- MODX 2.4.x++ (tested). But also should work on MODX version 2.2.2++ or 2.3.x++ (need a feedback)
- PHP 5.x++ with LDAP module enable. For PHP 5.6 or newer you will need to compile PHP with OpenLDAP 2.4 or newer (for more information see http://php.net/manual/en/ldap.setup.php ).
- Any LDAP server to work with, including OpenLDAP and Microsoft Active Directory.
